FROM node:alpine


WORKDIR /app
COPY package.json /app
RUN npm install

COPY ./ /app/

CMD [ "npm","run","start" ]

# runing docker dev file
# docker build -f Dockerfile.dev .

# docker run -p 3000:3000 -v /app/node_modules -v $(pwd):/app (image-id)

# testing in docker env
# docker run -it (container-id)  npm run test