version: "3"
services:
  web:
    build: 
      context: . # Context where current working directory or specific folder.
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app  # out container folder : inside container folder
  tests:
    build: 
      context: . # Context where current working directory or specific folder.
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app  # out container folder : inside container folder
    command: ["npm","run","test"]